export interface ComponentEntry {
  name: string
  plate: string
  description: string
  file: string // caminho relativo à raiz da Vernier
  localDeps: string[] // outros arquivos da Vernier que este componente precisa (ex: lib/cn.ts)
  npmDeps: string[] // pacotes do package.json que este componente exige
}

// Isso é a fonte única de verdade que list_components/get_component/install_component
// usam. Ao adicionar um componente novo na Vernier, adicione a entrada aqui — é o
// "índice do catálogo" que o MCP lê, não uma varredura automática de pasta (mais
// previsível, sem precisar parsear TSX pra adivinhar dependência).
export const manifest: ComponentEntry[] = [
  {
    name: 'Button',
    plate: '01',
    description: 'Botão com variantes primary/secondary/ghost/danger/gradient/forged/glow, tamanhos sm/md/lg/icon, loading.',
    file: 'src/components/Button.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Input',
    plate: '02',
    description: 'Campo de texto com label, dica e estado de erro tratado com texto explicativo.',
    file: 'src/components/Input.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Textarea',
    plate: '03',
    description: 'Área de texto multilinha com label, dica e erro — mesma voz do Input.',
    file: 'src/components/Textarea.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Card',
    plate: '04',
    description: 'Superfície de cartão com Header, Title, Description e Content.',
    file: 'src/components/Card.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Badge',
    plate: '05',
    description: 'Selo de status com tons neutral/brass/verdigris/rust.',
    file: 'src/components/Badge.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Switch',
    plate: '06',
    description: 'Interruptor on/off acessível (Radix).',
    file: 'src/components/Switch.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-switch'],
  },
  {
    name: 'Checkbox',
    plate: '06',
    description: 'Caixa de seleção acessível (Radix), com ícone de check.',
    file: 'src/components/Checkbox.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-checkbox', 'lucide-react'],
  },
  {
    name: 'Select',
    plate: '07',
    description: 'Seletor acessível (Radix) com trigger, conteúdo, item, label e separador.',
    file: 'src/components/Select.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-select', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Tabs',
    plate: '08',
    description: 'Abas acessíveis (Radix) com indicador de aba ativa em brass.',
    file: 'src/components/Tabs.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-tabs'],
  },
  {
    name: 'DropdownMenu',
    plate: '09',
    description: 'Menu suspenso acessível (Radix), com item, separador e variante destrutiva.',
    file: 'src/components/DropdownMenu.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-dropdown-menu', 'tailwindcss-animate'],
  },
  {
    name: 'Tooltip',
    plate: '10',
    description: 'Dica flutuante acessível (Radix), com seta e atraso de exibição configurado.',
    file: 'src/components/Tooltip.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-tooltip'],
  },
  {
    name: 'Dialog',
    plate: '11',
    description: 'Diálogo/modal acessível (Radix), com overlay, título, descrição e botão de fechar.',
    file: 'src/components/Dialog.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-dialog', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Table',
    plate: '12',
    description: 'Tabela densa com convenção contábil: coluna numérica alinhada à direita em monoespaçada.',
    file: 'src/components/Table.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Sidebar',
    plate: '13',
    description: 'Navegação lateral reutilizável, com marca, itens ativos/inativos e rodapé opcional.',
    file: 'src/components/Sidebar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Alert',
    plate: '14',
    description: 'Alerta persistente na página com tons neutral/brass/verdigris/rust e ícones padrão.',
    file: 'src/components/Alert.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Progress',
    plate: '15',
    description: 'Barra de medição com label, percentual em mono e modo indeterminado.',
    file: 'src/components/Progress.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Skeleton',
    plate: '16',
    description: 'Placeholder de carregamento com formas line/circle/block e pulso discreto.',
    file: 'src/components/Skeleton.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Toast',
    plate: '17',
    description: 'Notificação efêmera via ToastProvider + useToast(), com tons e auto-dismiss.',
    file: 'src/components/Toast.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Pagination',
    plate: '18',
    description: 'Paginação com elipses inteligentes, números em mono e página ativa em brass.',
    file: 'src/components/Pagination.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'EmptyState',
    plate: '19',
    description: 'Estado vazio com ícone, título, descrição e slot de ação — tela vazia como convite.',
    file: 'src/components/EmptyState.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Kbd',
    plate: '20',
    description: 'Tecla de atalho tipográfica em mono, com borda inferior mais pesada.',
    file: 'src/components/Kbd.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'IconButton',
    plate: '21',
    description: 'Botão só de ícone com tons brass/verdigris/rust/neutral e gradiente de painel.',
    file: 'src/components/IconButton.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Gauge',
    plate: '22',
    description: 'Manômetro circular SVG (arco 270°) com glow, tons e valor mono no centro.',
    file: 'src/components/Gauge.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Stat',
    plate: '23',
    description: 'Cartão de métrica com label mono, valor display, delta e vinheta de latão.',
    file: 'src/components/Stat.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'SegmentedControl',
    plate: '24',
    description: 'Seletor multiposição com trilho escavado e segmento ativo em latão fundido.',
    file: 'src/components/SegmentedControl.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Callout',
    plate: '25',
    description: 'Bloco editorial com trilho metálico à esquerda e wash de tom.',
    file: 'src/components/Callout.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Avatar',
    plate: '26',
    description: 'Avatar com iniciais, ring tonal e gradiente de fundo.',
    file: 'src/components/Avatar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Chip',
    plate: '27',
    description: 'Chip selecionável/removível com estados idle e latão fundido.',
    file: 'src/components/Chip.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'StatusDot',
    plate: '28',
    description: 'LED de status com glow e pulse opcional.',
    file: 'src/components/StatusDot.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Divider',
    plate: '29',
    description: 'Separador com gradiente; modo ornate com label entre filetes de latão.',
    file: 'src/components/Divider.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Slider',
    plate: '30',
    description: 'Range nativo estilizado com polegar de latão (WebKit/Firefox).',
    file: 'src/components/Slider.tsx',
    localDeps: ['src/lib/cn.ts', 'src/index.css'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Breadcrumb',
    plate: '31',
    description: 'Trilha de navegação com item atual em brass-bright.',
    file: 'src/components/Breadcrumb.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Timeline',
    plate: '32',
    description: 'Linha do tempo com dots luminosos e meta tipográfica mono.',
    file: 'src/components/Timeline.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'InstrumentCard',
    plate: '33',
    description: 'Cartão premium com borda em gradiente de latão, vinheta e glow opcional.',
    file: 'src/components/InstrumentCard.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
]

export function findComponent(name: string): ComponentEntry | undefined {
  return manifest.find((c) => c.name.toLowerCase() === name.toLowerCase())
}
