export interface ComponentEntry {
  name: string
  plate: string
  description: string
  file: string // caminho relativo à raiz da Vernier
  localDeps: string[] // outros arquivos da Vernier que este componente precisa (ex: lib/cn.ts)
  npmDeps: string[] // pacotes do package.json que este componente exige
}

// Isso é a fonte única de verdade que list_components/get_component/install_component
// usam. Ao adicionar um componente novo na Vernier, adicione a entrada aqui — é o
// "índice do catálogo" que o MCP lê, não uma varredura automática de pasta (mais
// previsível, sem precisar parsear TSX pra adivinhar dependência).
export const manifest: ComponentEntry[] = [
  {
    name: 'Button',
    plate: '01',
    description: 'Botão com variantes primary/secondary/ghost/danger/gradient/forged/glow, tamanhos sm/md/lg/icon, loading.',
    file: 'src/components/Button.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Input',
    plate: '02',
    description: 'Campo de texto com label, dica e estado de erro tratado com texto explicativo.',
    file: 'src/components/Input.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Textarea',
    plate: '03',
    description: 'Área de texto multilinha com label, dica e erro — mesma voz do Input.',
    file: 'src/components/Textarea.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Card',
    plate: '04',
    description: 'Superfície de cartão com Header, Title, Description e Content.',
    file: 'src/components/Card.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Badge',
    plate: '05',
    description: 'Selo de status com tons neutral/brass/verdigris/rust.',
    file: 'src/components/Badge.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Switch',
    plate: '06',
    description: 'Interruptor on/off acessível (Radix).',
    file: 'src/components/Switch.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-switch'],
  },
  {
    name: 'Checkbox',
    plate: '06',
    description: 'Caixa de seleção acessível (Radix), com ícone de check.',
    file: 'src/components/Checkbox.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-checkbox', 'lucide-react'],
  },
  {
    name: 'Select',
    plate: '07',
    description: 'Seletor acessível (Radix) com trigger, conteúdo, item, label e separador.',
    file: 'src/components/Select.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-select', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Tabs',
    plate: '08',
    description: 'Abas acessíveis (Radix) com indicador de aba ativa em brass.',
    file: 'src/components/Tabs.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-tabs'],
  },
  {
    name: 'DropdownMenu',
    plate: '09',
    description: 'Menu suspenso acessível (Radix), com item, separador e variante destrutiva.',
    file: 'src/components/DropdownMenu.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-dropdown-menu', 'tailwindcss-animate'],
  },
  {
    name: 'Tooltip',
    plate: '10',
    description: 'Dica flutuante acessível (Radix), com seta e atraso de exibição configurado.',
    file: 'src/components/Tooltip.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-tooltip'],
  },
  {
    name: 'Dialog',
    plate: '11',
    description: 'Diálogo/modal acessível (Radix), com overlay, título, descrição e botão de fechar.',
    file: 'src/components/Dialog.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-dialog', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Table',
    plate: '12',
    description: 'Tabela densa com convenção contábil: coluna numérica alinhada à direita em monoespaçada.',
    file: 'src/components/Table.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Sidebar',
    plate: '13',
    description: 'Navegação lateral reutilizável, com marca, itens ativos/inativos e rodapé opcional.',
    file: 'src/components/Sidebar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Alert',
    plate: '14',
    description: 'Alerta persistente na página com tons neutral/brass/verdigris/rust e ícones padrão.',
    file: 'src/components/Alert.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Progress',
    plate: '15',
    description: 'Barra de medição com label, percentual em mono e modo indeterminado.',
    file: 'src/components/Progress.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Skeleton',
    plate: '16',
    description: 'Placeholder de carregamento com formas line/circle/block e pulso discreto.',
    file: 'src/components/Skeleton.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Toast',
    plate: '17',
    description: 'Notificação efêmera via ToastProvider + useToast(), com tons e auto-dismiss.',
    file: 'src/components/Toast.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Pagination',
    plate: '18',
    description: 'Paginação com elipses inteligentes, números em mono e página ativa em brass.',
    file: 'src/components/Pagination.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'EmptyState',
    plate: '19',
    description: 'Estado vazio com ícone, título, descrição e slot de ação — tela vazia como convite.',
    file: 'src/components/EmptyState.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Kbd',
    plate: '20',
    description: 'Tecla de atalho tipográfica em mono, com borda inferior mais pesada.',
    file: 'src/components/Kbd.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'IconButton',
    plate: '21',
    description: 'Botão só de ícone com tons brass/verdigris/rust/neutral e gradiente de painel.',
    file: 'src/components/IconButton.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Gauge',
    plate: '22',
    description: 'Manômetro circular SVG (arco 270°) com glow, tons e valor mono no centro.',
    file: 'src/components/Gauge.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Stat',
    plate: '23',
    description: 'Cartão de métrica com label mono, valor display, delta e vinheta de latão.',
    file: 'src/components/Stat.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'SegmentedControl',
    plate: '24',
    description: 'Seletor multiposição com trilho escavado e segmento ativo em latão fundido.',
    file: 'src/components/SegmentedControl.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Callout',
    plate: '25',
    description: 'Bloco editorial com trilho metálico à esquerda e wash de tom.',
    file: 'src/components/Callout.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Avatar',
    plate: '26',
    description: 'Avatar com iniciais, ring tonal e gradiente de fundo.',
    file: 'src/components/Avatar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Chip',
    plate: '27',
    description: 'Chip selecionável/removível com estados idle e latão fundido.',
    file: 'src/components/Chip.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'StatusDot',
    plate: '28',
    description: 'LED de status com glow e pulse opcional.',
    file: 'src/components/StatusDot.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Divider',
    plate: '29',
    description: 'Separador com gradiente; modo ornate com label entre filetes de latão.',
    file: 'src/components/Divider.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Slider',
    plate: '30',
    description: 'Range nativo estilizado com polegar de latão (WebKit/Firefox).',
    file: 'src/components/Slider.tsx',
    localDeps: ['src/lib/cn.ts', 'src/index.css'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Breadcrumb',
    plate: '31',
    description: 'Trilha de navegação com item atual em brass-bright.',
    file: 'src/components/Breadcrumb.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Timeline',
    plate: '32',
    description: 'Linha do tempo com dots luminosos e meta tipográfica mono.',
    file: 'src/components/Timeline.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'InstrumentCard',
    plate: '33',
    description: 'Cartão premium com borda em gradiente de latão, vinheta e glow opcional.',
    file: 'src/components/InstrumentCard.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Typography',
    plate: '00',
    description: 'Sistema tipográfico: Display, Heading, Lead, Text, Caption, Overline, InlineCode, Prose.',
    file: 'src/components/Typography.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'SearchInput',
    plate: '34',
    description: 'Campo de busca com ícone e limpar.',
    file: 'src/components/SearchInput.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'PasswordInput',
    plate: '34',
    description: 'Campo de senha com toggle mostrar/ocultar.',
    file: 'src/components/PasswordInput.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'NumberField',
    plate: '35',
    description: 'Stepper numérico com botões +/- e mono.',
    file: 'src/components/NumberField.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'RadioGroup',
    plate: '35',
    description: 'Grupo de rádio acessível (Radix) com indicador de latão.',
    file: 'src/components/RadioGroup.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-radio-group'],
  },
  {
    name: 'Accordion',
    plate: '36',
    description: 'Accordion acessível (Radix) com chevron e animação de altura.',
    file: 'src/components/Accordion.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-accordion', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Collapsible',
    plate: '37',
    description: 'Conteúdo recolhível (Radix).',
    file: 'src/components/Collapsible.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-collapsible'],
  },
  {
    name: 'Popover',
    plate: '37',
    description: 'Popover flutuante (Radix) com painel de latão.',
    file: 'src/components/Popover.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-popover', 'tailwindcss-animate'],
  },
  {
    name: 'Sheet',
    plate: '38',
    description: 'Painel lateral/drawer (Dialog Radix) com slide por lado.',
    file: 'src/components/Sheet.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-dialog', 'lucide-react', 'tailwindcss-animate'],
  },
  {
    name: 'Spinner',
    plate: '39',
    description: 'Indicador de carregamento circular em brass.',
    file: 'src/components/Spinner.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Banner',
    plate: '39',
    description: 'Faixa de anúncio com tom e slot de ação.',
    file: 'src/components/Banner.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'FileDropzone',
    plate: '40',
    description: 'Área de upload por drag-and-drop.',
    file: 'src/components/FileDropzone.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Stepper',
    plate: '40',
    description: 'Passos de fluxo com estados done/active/todo.',
    file: 'src/components/Stepper.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Navbar',
    plate: '41',
    description: 'Barra de navegação com brand, links e actions.',
    file: 'src/components/Navbar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'CodeBlock',
    plate: '42',
    description: 'Bloco de código com botão copiar e chrome de terminal.',
    file: 'src/components/CodeBlock.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'HoverCard',
    plate: '42',
    description: 'Card ao hover (Radix) pra preview de perfil/entidade.',
    file: 'src/components/HoverCard.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-hover-card', 'tailwindcss-animate'],
  },
  {
    name: 'ScrollArea',
    plate: '43',
    description: 'Área com scroll customizado (Radix).',
    file: 'src/components/ScrollArea.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-scroll-area'],
  },
  {
    name: 'AspectRatio',
    plate: '43',
    description: 'Container de proporção fixa pra mídia.',
    file: 'src/components/AspectRatio.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Field',
    plate: '44',
    description: 'Field + Fieldset pra compor formulários com label/hint/erro.',
    file: 'src/components/Field.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Label',
    plate: '44',
    description: 'Label acessível (Radix).',
    file: 'src/components/Label.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-label'],
  },
  {
    name: 'Link',
    plate: '00',
    description: 'Link tipográfico com tons brass/muted/subtle.',
    file: 'src/components/Link.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Blockquote',
    plate: '00',
    description: 'Citação editorial em Fraunces itálico com filete de latão.',
    file: 'src/components/Blockquote.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Layout',
    plate: '41',
    description: 'Primitives de layout: Container, Stack, Inline.',
    file: 'src/components/Layout.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Separator',
    plate: '29',
    description: 'Separador simples horizontal/vertical (Radix).',
    file: 'src/components/Separator.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-separator'],
  },
  {
    name: 'CopyButton',
    plate: '42',
    description: 'Botão de ícone que copia texto pra clipboard.',
    file: 'src/components/CopyButton.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/IconButton.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'AlertDialog',
    plate: '45',
    description: 'Diálogo de confirmação (Radix Alert Dialog) pra ações destrutivas.',
    file: 'src/components/AlertDialog.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-alert-dialog', 'tailwindcss-animate'],
  },
  {
    name: 'FormDialog',
    plate: '45',
    description: 'Modal de formulário pronto com trigger, campos e ações.',
    file: 'src/components/FormDialog.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Dialog.tsx', 'src/components/Button.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'CommandPalette',
    plate: '46',
    description: 'Palette de comandos com busca e grupos.',
    file: 'src/components/CommandPalette.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Dialog.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'ContextMenu',
    plate: '47',
    description: 'Menu de contexto (botão direito) acessível (Radix).',
    file: 'src/components/ContextMenu.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-context-menu', 'tailwindcss-animate'],
  },
  {
    name: 'AppShell',
    plate: '48',
    description: 'Shell de app com sidebar + topbar + área de conteúdo.',
    file: 'src/components/AppShell.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/SearchInput.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'SidebarNav',
    plate: '48',
    description: 'Sidebar com seções, badges e modo recolhido.',
    file: 'src/components/SidebarNav.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Forms',
    plate: '49',
    description: 'FormCard, LoginForm e SettingsForm compostos.',
    file: 'src/components/Forms.tsx',
    localDeps: [
      'src/lib/cn.ts',
      'src/components/Button.tsx',
      'src/components/Input.tsx',
      'src/components/PasswordInput.tsx',
      'src/components/Textarea.tsx',
      'src/components/Checkbox.tsx',
      'src/components/Switch.tsx',
      'src/components/Field.tsx',
      'src/components/Select.tsx',
    ],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Footer',
    plate: '52',
    description: 'Rodapé de site com colunas de links, marca e legal.',
    file: 'src/components/Footer.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Link.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Hero',
    plate: '53',
    description: 'Hero de landing com eyebrow, CTAs e slot de mídia.',
    file: 'src/components/Hero.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx', 'src/components/Typography.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'PricingCards',
    plate: '54',
    description: 'Cards de planos com destaque popular e lista de features.',
    file: 'src/components/PricingCards.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx', 'src/components/Badge.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Combobox',
    plate: '55',
    description: 'Select com busca (popover + filtro).',
    file: 'src/components/Combobox.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Popover.tsx', 'src/components/Button.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Calendar',
    plate: '56',
    description: 'Calendário mensal pra seleção de data.',
    file: 'src/components/Calendar.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'DataTable',
    plate: '57',
    description: 'Tabela com busca, sort e seleção de linhas.',
    file: 'src/components/DataTable.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Checkbox.tsx', 'src/components/SearchInput.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'MobileNav',
    plate: '58',
    description: 'Navbar mobile com menu em Sheet.',
    file: 'src/components/MobileNav.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx', 'src/components/Sheet.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'Menubar',
    plate: '59',
    description: 'Barra de menus estilo desktop (Radix).',
    file: 'src/components/Menubar.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-menubar', 'tailwindcss-animate'],
  },
  {
    name: 'OtpInput',
    plate: '60',
    description: 'Input de OTP/PIN com paste e navegação por teclado.',
    file: 'src/components/OtpInput.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'ToggleGroup',
    plate: '61',
    description: 'Toggle e ToggleGroup (Radix) pra ações e alinhamento.',
    file: 'src/components/ToggleGroup.tsx',
    localDeps: ['src/lib/cn.ts'],
    npmDeps: ['clsx', 'tailwind-merge', '@radix-ui/react-toggle', '@radix-ui/react-toggle-group'],
  },
  {
    name: 'Carousel',
    plate: '62',
    description: 'Carrossel de slides com dots e setas.',
    file: 'src/components/Carousel.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx'],
    npmDeps: ['clsx', 'tailwind-merge', 'lucide-react'],
  },
  {
    name: 'CookieBanner',
    plate: '63',
    description: 'Banner de consentimento de cookies.',
    file: 'src/components/CookieBanner.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'ErrorPage',
    plate: '64',
    description: 'Página de erro 404/500 com CTA.',
    file: 'src/components/ErrorPage.tsx',
    localDeps: ['src/lib/cn.ts', 'src/components/Button.tsx', 'src/components/Typography.tsx'],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
  {
    name: 'Wizard',
    plate: '65',
    description: 'Fluxo multi-step com validação e Stepper.',
    file: 'src/components/Wizard.tsx',
    localDeps: [
      'src/lib/cn.ts',
      'src/components/Button.tsx',
      'src/components/Stepper.tsx',
      'src/components/Input.tsx',
      'src/components/Textarea.tsx',
    ],
    npmDeps: ['clsx', 'tailwind-merge'],
  },
]

export function findComponent(name: string): ComponentEntry | undefined {
  return manifest.find((c) => c.name.toLowerCase() === name.toLowerCase())
}
